# -*- coding: utf-8 -*-
"""MLModel

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_eWKF_VUoj7FHln6KXljHk_uA4QJbFNy
"""

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

data = pd.read_csv("/content/Crop_recommendation.csv")

data.head()

data.shape

data.isnull().sum()

# splitting features and labels

x = data.iloc[:,:-1]#features ; loading first 7 cols to x
y = data.iloc[:,-1] #labels ; loading the last col to y, ":"-means all col

x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=42)

x_train.head()

y_train.head()

model = RandomForestClassifier()

model.fit(x_train,y_train)

prediction = model.predict(x_test)

accuracy = model.score(x_test, y_test)

print(accuracy)

new_features = [[36,58,25,28.66024,59.31891,8.399136,36.9263]]
predicted_crop = model.predict(new_features)
print(predicted_crop)

